version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync public/ s3://engineerbeard.com/ --region us-east-1 --delete --acl public-read
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*